# Generated by Django 2.1.2 on 2018-12-02 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='pub_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
